echo "# Test1" >> README.md 
git init 
git add README.md 
git commit -m "primeiro commit" 
git branch -M main 
git remote add origin https://github.com/wellgabriel472-creator/Test1.git
 git push -u origin main
